# Generated by Django 3.2.8 on 2021-11-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211123_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatas',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.usernames'),
        ),
    ]
